### ISSUE TITLE
density_thresh

### ISSUE THREAD

**Issue by cv-lab-x** [kwea123/ngp_pl#103]
HI, thanks for your greate work! I have a little question about the density threshold, why do you use density_thresh = 0.01*MAX_SAMPLES/3**0.5 in training progress, but use density_thresh with 0.01 when test ?

self.model.update_density_grid(0.01*MAX_SAMPLES/3**0.5,
                                           warmup=self.global_step<self.warmup_steps,
                                           erode=self.hparams.dataset_name=='colmap')

@kwea123 looking forward to your reply, thanks!

**Comment by kwea123** [comment]
the density threshold only have effect when training, when testing the occupancy grid is fixed.
