### ISSUE TITLE
Failure to load state dict

### ISSUE THREAD

**Issue by Francisco21145** [kwea123/ngp_pl#105]
First I want to say thank you for making this amazing peace of software, and made it open!!
I have a problem here.
After I train the model I try the test.ipynb notebook and when I try to use the function load_ckpt from utils it says size mismatch. 
And I don't know why.

![aws_error2](https://user-images.githubusercontent.com/84643256/205112568-19493192-6842-4108-8e5d-3a2b3e4e9b94.png)
![aws_error](https://user-images.githubusercontent.com/84643256/205111711-737c9496-cb97-4074-9c6c-e0fc657b5c61.png)

I am using aws ec2-instance, a p3.2xlarge with ubuntu 20.04.
I installed everything and it seems like everything is working, but for some reason it ain't.
Thank you in advance

**Comment by kwea123** [comment]
Set the `scale` in `NGP` to `0.5` if you're using the provided pretrained model
