### ISSUE TITLE
Checkpoint can't be loaded. Unexpected keys in state_dict

### ISSUE THREAD

**Issue by salykova** [kwea123/ngp_pl#117]
Hello @kwea123 !

After successful training on colmap dataset, I tried to load checkpoint and test the trained model. However I got the following error ```Unexpected key(s) in state_dict: "directions", "poses". ```.

Train parameters
``` python train.py --root_dir scene path --dataset_name colmap --exp_name scene --scale 8 --num_epochs 5 --distortion_loss_w 1e-2 --batch_size 4096 --downsample 0.4 ```

Checkpoint load parameters
```python train.py --root_dir scene path --dataset_name colmap --exp_name scene --scale 8 --num_epochs 5 --distortion_loss_w 1e-2 --batch_size 4096 --downsample 0.4  --val_only --ckpt_path=path to checkpoint```

Error
```
Restoring states from the checkpoint path at /home/slkv/Documents/projects/ngp_pl/ckpts/ours/canister/epoch=0.ckpt
Traceback (most recent call last):
  File "train.py", line 278, in <module>
    trainer.fit(system, ckpt_path=hparams.ckpt_path)
  File "/home/slkv/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/home/slkv/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/slkv/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/slkv/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1110, in _run
    self._restore_modules_and_callbacks(ckpt_path)
  File "/home/slkv/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1065, in _restore_modules_and_callbacks
    self._checkpoint_connector.restore_model()
  File "/home/slkv/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 182, in restore_model
    self.trainer.strategy.load_model_state_dict(self._loaded_checkpoint)
  File "/home/slkv/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 343, in load_model_state_dict
    self.lightning_module.load_state_dict(checkpoint["state_dict"])
  File "/home/slkv/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for NeRFSystem:
        Unexpected key(s) in state_dict: "directions", "poses". 
```

**Comment by salykova** [comment]
I use normal checkpoint, not slim

**Comment by za970120604** [comment]
same issue 

> I use normal checkpoint, not slim

hello , did you solve it ?? I use the colmap dataset , which is the same dataset type as  yours and I think I load the correct ckpt model , not slim , and still get the same error  as you got. Thanks a lot!

**Comment by salykova** [comment]
Hi @za970120604,

No, it doesn't work neither with slim nor with normal checkpoint ((( Hopefully @kwea123 can comment on this issue

**Comment by salykova** [comment]
Hi @za970120604,

There is a workaround to solve it: the following lines [#114](https://github.com/kwea123/ngp_pl/blob/1b49af1856a276b236e0f17539814134ed329860/train.py#L114), [#115](https://github.com/kwea123/ngp_pl/blob/master/train.py#L115) must be defined in ```setup()``` instead of ```configure_optimiziers()```

So, my ```setup()``` is
```
    def setup(self, stage):
        dataset = dataset_dict[self.hparams.dataset_name]
        kwargs = {'root_dir': self.hparams.root_dir,
                  'downsample': self.hparams.downsample}
        self.train_dataset = dataset(split=self.hparams.split, **kwargs)
        self.train_dataset.batch_size = self.hparams.batch_size
        self.train_dataset.ray_sampling_strategy = self.hparams.ray_sampling_strategy
        self.test_dataset = dataset(split='test', **kwargs)
        self.register_buffer('directions', self.train_dataset.directions.to(self.device))
        self.register_buffer('poses', self.train_dataset.poses.to(self.device))
```
Also [this line](https://github.com/kwea123/ngp_pl/blob/1b49af1856a276b236e0f17539814134ed329860/train.py#L254) should be ```save_weights_only=False ```. I used normal ckpts, not slim ckpts.

P.S. If you want to load a checkpoint and run only validation, use ``` trainer.validate(system, ckpt_path=hparams.ckpt_path) ```

**Comment by Shzhuoyu** [comment]
you are real hero!

**Comment by Moreland-cas** [comment]
Here is another way to solve it:
'''python
    system = NeRFSystem(hparams)
    if hparams.val_only:
        checkpoint = torch.load(hparams.ckpt_path, map_location=torch.device('cpu'))
        system.load_state_dict(checkpoint['state_dict'], strict=False)
        trainer.validate(system)
    else:
        trainer.fit(system)
'''
