### ISSUE TITLE
some question about the c2w

### ISSUE THREAD

**Issue by Benjobs1** [kwea123/ngp_pl#120]
I have a question about this: my dataset was rendered in blender, and the blender coordinate system is [back, right, up], the camera pose was based on blender's world coordinate, I wonder how to convert the pose to your coordinate system. I don't understand your process about the camera pose : c2w. Is this equivalent to transforming the position by multiplying the rotation matrix left？
https://github.com/kwea123/ngp_pl/blob/1b49af1856a276b236e0f17539814134ed329860/datasets/nsvf.py#L70
![image](https://user-images.githubusercontent.com/58802128/220867905-2ffb5af5-0608-4e24-ae0f-09faaf369d5f.png)

**Comment by Benjobs1** [comment]
Sorry, I have solved this problem, it's a brilliant tool.

**Comment by Hippogriff** [comment]
@Benjobs1 How did you solve this problem? I am also struggling with this problem?

**Comment by Benjobs1** [comment]
> @Benjobs1 How did you solve this problem? I am also struggling with this problem?

In my case, my camera pose rendered by blender was w2c, I just transpose the matrix to c2w.I haven't changed anything else.
