### ISSUE TITLE
Error about running "pip install models/csrc/"

### ISSUE THREAD

**Issue by ThreeBoxWithCode** [kwea123/ngp_pl#125]
Hi @kwea123 , thank you for this wonderful implementation
When I run "pip install models/csrc/" in the codna virtual environment, the following error occurs:
====================================================================================
(ngp_pl) threebox@threebox-VivoBook-ASUSLaptop-X571GT-VX60GT:~/NeRF/ngp_pl$ pip install models/csrc/
Processing ./models/csrc
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: vren
  Building wheel for vren (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      running bdist_wheel
      running build
      running build_ext
      error: [Errno 2] No such file or directory: '/usr/local/cuda:/bin/nvcc'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for vren
  Running setup.py clean for vren
Failed to build vren
Installing collected packages: vren
  Running setup.py install for vren ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for vren did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      running install
      /home/threebox/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      error: [Errno 2] No such file or directory: '/usr/local/cuda:/bin/nvcc'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> vren

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

====================================================================================
I search the /usr/local/cuda:/bin/nvcc, discover it exists.
In the codna virtual environment, my cuda version is 11.3, and in the base environment is cuda11.7
![image](https://user-images.githubusercontent.com/99881856/225932081-028b585c-6d98-4295-aac8-d1c8a530c363.png)
I would like to know whether this error is related to cuda version in my base environment. Looking forward to your clarification

**Comment by tommoy** [comment]
check if the version of  torch and torchvision is correct

**Comment by konderex** [comment]
Hi,I met the same problem,I wonder how did you solve it.
