### ISSUE TITLE
Question about density grid?

### ISSUE THREAD

**Issue by AlexRoss-WHS** [kwea123/ngp_pl#13]
Hi,
in [models/networks.py on line 160](https://github.com/kwea123/ngp_pl/blob/a7329b465a5a0c75b886913d371907811c9ac7d8/models/networks.py#L160) should't it say `s = min(2**(c - 1), self.scale)` instaed of `s = min(2**c, self.scale)`, in accordance with the comment on [line 20](https://github.com/kwea123/ngp_pl/blob/a7329b465a5a0c75b886913d371907811c9ac7d8/models/networks.py#L20)?  
If I'm wrong could you explain why?

**Comment by kwea123** [comment]
Thanks for spotting this, you are correct. I fixed it. Currently cascade is always 1 and scale is 0.5 so I hope nothing is changed actually.
