### ISSUE TITLE
RayMarcher的backward是不必要的

### ISSUE THREAD

**Issue by xiaoc57** [kwea123/ngp_pl#138]
我发现在py文件的RayMarcher中有backward的静态方法，计算过程是正确的，但是rays_o and rays_d是不需要梯度的tensor，所以这步反向传播是不是不需要的？？
我刚刚入门cuda，对这个位置比较迷惑

**Comment by SCUTykLin** [comment]
这是为了对位姿进行优化

**Comment by C2022G** [comment]
不是很理解，能详细解释一下吗？计算过程和为什么对位姿进行优化

**Comment by xiaoc57** [comment]
> 不是很理解，能详细解释一下吗？计算过程和为什么对位姿进行优化

我看到代码中有一部分写的是直接将位姿设置为可学习的参数，这样就可以不利用输入的位姿，直接优化就行。
计算过程大概就是链式计算，你可以看看这个repo的那个人在YouTube上讲的cuda教程。
