### ISSUE TITLE
Exporting model as ONNX for inference using barracuda.

### ISSUE THREAD

**Issue by cubantonystark** [kwea123/ngp_pl#14]
I wonder if once you are able to create the custom dataset pipeline, it would be an issue to try and deploy the resulting NGP into unity via barracuda. I presume exporting the model to ONNX and running it through barracuda wouldn't be much of an issue? I foresee using the a pipeline closely related to the Style Transfer One.

**Comment by kwea123** [comment]
I use `tinycudann`, and am unsure that library supports onnx. You are free to try, but it's not in my plan currently
