### ISSUE TITLE
Demo using Lightning App ⚡️

### ISSUE THREAD

**Issue by aniketmaurya** [kwea123/ngp_pl#15]
Hi @kwea123, thanks for providing the pre-trained checkpoints. I loved this project 😄 ! 

Do you have any plan to add a demo app for this? You can create a [Lightning App](https://lightning.ai/apps) and submit it to the app gallery.

We've created [Research Template App](https://github.com/Lightning-AI/LAI-research-template-App) for this purpose, his app lets you connect a blogpost, arxiv paper, and a jupyter notebook and even have an interactive demo for people to play with the model. This app also allows industry practitioners to reproduce your work.

---
PS: I'd be interested in contributing by creating an app for this project.

**Comment by kwea123** [comment]
Hi, is [this](https://github.com/kwea123/kwea123/issues/19) for the same purpose? I'll ping you in slack!
