### ISSUE TITLE
Multi GPU Training Support

### ISSUE THREAD

**Issue by MultiPath** [kwea123/ngp_pl#16]
Hi, thanks for the amazing code!
Although the original tcnn codebase stated that they did not support multi-GPU.
https://github.com/NVlabs/tiny-cuda-nn/issues/63

But I found that as long as you set
```
torch.cuda.set_device(rank)
```
before calling anything like ``tcnn.Network``, it actually works. All the tensors are in the correct GPUs and behave normal to me.
And it is also common to ``set_device`` in distributed training before setting ``dist.init_process_group``

However, I am completely new to pytorch-lighting and not sure how the DDP was implemented.
I tried to do it naviely but the code raise errors about "illegal memory access".
I am not sure if it is due to improper DDP settings, or your custom cuda code like "aabb_intersection" or "density_grid update".

Personally I think it will be very useful if the code supports multi-gpu which can be potentially used in multi-object/video data scenarios.

**Comment by MultiPath** [comment]
tcnn seems also officially support multi-GPU just now
https://github.com/NVlabs/tiny-cuda-nn/pull/120

**Comment by kwea123** [comment]
Thank you! will try this very soon

**Comment by MultiPath** [comment]
I looked at PL's doc and found a way to fix it now. Basically, you can just initialize the model in ``setup()`` of LightningModule.
A code snippet is as follows:
```
    def setup(self, stage):
        hparams = self.hparams
        dataset = dataset_dict[hparams.dataset_name]
        kwargs = {'root_dir': hparams.root_dir,
                  'downsample': hparams.downsample}
        
        # setup dataset
        self.train_dataset = dataset(split=hparams.split, **kwargs)
        self.test_dataset = dataset(split='test', **kwargs)

        # build model
        self.loss = NeRFLoss()
        self.model = NGP(scale=hparams.scale)
        
        # save grid coordinates for training
        G = self.model.grid_size
        self.model.register_buffer('grid_coords',
            create_meshgrid3d(G, G, G, False, dtype=torch.int32).reshape(-1, 3))
```

Other small fixes to do are computing PSNR and saving videos after gathering all tensors using ``pytorch_lightning.utilities.distributed.all_gather_ddp_if_available``

The results seem ok to me, however, I found the number slightly different from a single GPU.

https://user-images.githubusercontent.com/5780274/178849936-70664136-1f8d-4998-b8b0-3ce9a9968bad.mp4

If needed, I can also make a pull request but I think you can write in a cleaner way..

**Comment by kwea123** [comment]
Ok, I also succeed in using multi-gpu (tested with 2 now, but should work for any number). To get the correct PSNR, I need to use [torchmetrics](https://torchmetrics.readthedocs.io/en/stable/). I will update once it is done, thank you!

**Comment by kwea123** [comment]
The work is done! I've tested with 2 GPUs and 8GPUs and they work correctly. With the same parameters, however, the performance seem to degrade a bit (35.8 -> 35.5 for Lego with 2 gpus), it might require parameter tuning to get the same performance, but now multi-gpu is ready!

**Comment by kwea123** [comment]
I also observed that with more gpus, the training speed seems to be slower...

**Comment by MultiPath** [comment]
> I also observed that with too many gpus (8), the training speed seems to be slower...

I think this makes sense. Using multi-GPU will give additional overhead, but it "may" give you more flexibility in the future.

Also, I saw your implementation still initializes the model in __init__ instead of setup() function. Not sure why in my initial trial, it will give me illegal memory access. But if everything works smoothly in your code, maybe I did not do things right in other places.

**Comment by kwea123** [comment]
In pytorch-lightning, models (in fact all nn.modules or tensors, buffers) should be defined in `__init__` in order to be placed on the right device (e.g. in case of multi-gpu). `setup` is for defining datasets. You can try the latest code.

**Comment by MultiPath** [comment]
When it is initialized https://github.com/kwea123/ngp_pl/blob/master/train.py#L193
It has not entered into the Trainer yet so the model is initialized on gpu0, right?
Previously, I found that once tcnn was initialized on gpu0, it is not possible to reassign it to another gpu.
While setup is called after ddp is initialized

**Comment by kwea123** [comment]
Initially they are all on cpu, I'm not sure when they are transferred to the correct device. My practice is to initialize everything in `__init__`, and if something needs to be created later, I use `device=self.device` to place it correctly.

**Comment by MultiPath** [comment]
tcnn is only on GPU. Some simple codes you can find from the original issue of tcnn for multi-gpu support.
