### ISSUE TITLE
Results reproduction

### ISSUE THREAD

**Issue by YaroslavShchekaturov** [kwea123/ngp_pl#18]
Hi @kwea123 ! Thanks a lot for youe work!
I've tried to reproduce your results but I did not manage to achieve high quality. The only difference is that I used AdamW rather than apex fused optimizer. I tried Robot dataset with simply :
python train.py --root_dir C:\Users\Admin\Desktop\Robot --exp_name Lego --scale 1 

And I recieved the following results: 
![image](https://user-images.githubusercontent.com/22734034/178624410-b91e0012-32e0-4c9d-8ea2-2513238fb49d.png)
![003_d](https://user-images.githubusercontent.com/22734034/178624456-78b30954-31b4-404a-a328-69809c6aff9c.png)
![003](https://user-images.githubusercontent.com/22734034/178624540-7246f0df-e38f-4a77-9538-c148a4ab896c.png)

Is it a problem with a different optimizer or I should change some parameters?

**Comment by kwea123** [comment]
Hi, are you using the latest code? Please set `--scale 0.5`. I'm still debugging for scale>0.5 (real scenes) and having difficulties, but all the nsvf data should work with default settings.

**Comment by YaroslavShchekaturov** [comment]
Yep! I tried 0,5 also but got almost the same result. Is it a problem with optimiser?

**Comment by kwea123** [comment]
Can you first confirm that it works with the default optimizer? If so, then it's the problem of the optimizer. I've tried SGD, RAdam too and they didn't work either

**Comment by YaroslavShchekaturov** [comment]
@kwea123 Thanks! Ill try apex optimizer, I did not do it yet because It is not easy to install it with Windows. I suppose that there is a problem with a regular Adam when we use mixed precision.

**Comment by YaroslavShchekaturov** [comment]
Hi @kwea123! I've tried training wi9th the default optimizer and rusult does not change 
![image](https://user-images.githubusercontent.com/22734034/178742762-fb2aca0c-9821-405f-85aa-042d5783d63e.png)
![000](https://user-images.githubusercontent.com/22734034/178742826-369f5d31-30cd-41cb-93a5-2c02c2587785.png)

**Comment by kwea123** [comment]
So you're using windows? I'll try when I have time, but bare in mind that this repo is for research purpose so if I can't find an easy way to solve this problem with windows, this issue will be "won't fix". Thanks for your comprehension.

**Comment by YaroslavShchekaturov** [comment]
Sure! No problem!

**Comment by zjjMaiMai** [comment]
> @kwea123 Thanks! Ill try apex optimizer, I did not do it yet because It is not easy to install it with Windows. I suppose that there is a problem with a regular Adam when we use mixed precision.

i replace apex FusedAdam to torch.optim.Adam and get psnr=34.30 on lego scene.
```
(base) D:\ngp_pl>python train.py --root_dir E:\Synthetic_NeRF\Synthetic_NeRF\Lego --exp_name Lego --scale 1 --batch_size 4096
GridEncoding: Nmin=16 b=1.38191 F=2 T=2^19 L=16
Using 16bit native Automatic Mixed Precision (AMP)
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
GridEncoding: Nmin=16 b=1.38191 F=2 T=2^19 L=16
Using 16bit native Automatic Mixed Precision (AMP)
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: logs\Lego                                                                                                                                                 508, train/s_per_ray=73.60, train/psnr=23.30]
Loading 100 train images ...
100it [00:03, 28.70it/s]
Loading 200 test images ...
200it [00:06, 30.06it/s]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Epoch 0:  20%|███████████████████████▉                                                                                              | 203/1000 [00:13<00:54, 14.68it/s, loss=0.00Epoch 0:  20%|██████████████▋                                                         | 204/1000 [00:13<00:54, 14.73it/s, loss=0.00499, train/s_per_ray=71.90, train/psnr=23.20] 
Epoch 29: 100%|████████████████████████████████████████████████████| 1200/1200 [01:47<00:00, 11.13it/s, loss=0.000213, train/s_per_ray=23.10, train/psnr=36.50, test/psnr=34.30]
```

**Comment by zjjMaiMai** [comment]
I think there is not a platform related issue here after I fixed vren compile error.

**Comment by kwea123** [comment]
Thanks, btw you should use `scale=0.5` for maximal performance
