### ISSUE TITLE
Training and Rendering Bounding Box

### ISSUE THREAD

**Issue by bolopenguin** [kwea123/ngp_pl#19]
Hello!
Thanks for your work.
I just wanted to know if you plan to add the rendering bounding box, just like in Torch-NGP or Instant-NGP, in addition to the training bounding box.

**Comment by kwea123** [comment]
Hi, I don't understand the question? You mean GUI?
Also, I am still debugging custom data training, I haven't succeeded yet

**Comment by bolopenguin** [comment]
No, I don't mean the GUI.
I mean that at training time the rays are casted inside the training bounding box, but at inference time they are casted just inside the rendering bounding box.
In Torch-NGP this behaviour is controlled by these two lines of code:
`https://github.com/ashawkey/torch-ngp/blob/dd2add6e05fa06cf7e82116c49d797ebdc4b7de9/nerf/renderer.py#L84`
In this way the rendered images are are created according to the rendering bounding box.

**Comment by kwea123** [comment]
Thank you. However I'm still struggling with custom data training, it still doesn't work yet. I'll implement this functionality later
