### ISSUE TITLE
Multi GPU Support

### ISSUE THREAD

**Issue by satyajitghana** [kwea123/ngp_pl#2]
It would be awesome if it could support multi gpu. Higher batch size support, more images, higher aabb scale, all this would be possible !

thanks for your amazing work :)

**Comment by kwea123** [comment]
Sorry, `tinycudann` library that I use doesn't support multi-gpu https://github.com/NVlabs/tiny-cuda-nn/issues/63, so this cannot be done sadly :(

**Comment by kwea123** [comment]
#16 covers this, now I'm working on getting the correct val result and it should be very quick!
