### ISSUE TITLE
"mark_untrained_cells" should be "mark_invisible_cells"?

### ISSUE THREAD

**Issue by MultiPath** [kwea123/ngp_pl#21]
https://github.com/kwea123/ngp_pl/blob/05b4c3ed66054449fb0916c67eac802beb861483/train.py#L114

What is the function of doing this?

**Comment by kwea123** [comment]
Thanks, just fixed it. It is explicitly marking the density_grid cells that aren't visible to any cameras with density=-1, so that they won't be sampled in the update process
