### ISSUE TITLE
Should ``start_idx+N_samples>sigmas.size(0)``?

### ISSUE THREAD

**Issue by MultiPath** [kwea123/ngp_pl#23]
https://github.com/kwea123/ngp_pl/blob/0813fad1a46bacab8fd1a98e5573487c52f663e7/models/csrc/volumerendering.cu#L20

Hi, I noticed a tiny thing in this line. I am not sure if I understood it correctly... and I am not sure why having this judgment in the first place.  Does it seem to cause the "last ray" always returns zero RGB?

Thanks

**Comment by kwea123** [comment]
wow, thanks for spotting this huge bug! You are right, it makes the last ray always be 0 RGB, I will quickly fix this and commit! Re-doing benchmarking...

**Comment by kwea123** [comment]
On test set the number doesn't seem to vary a lot (training psnr increases a lot!), so I'll leave the benchmark the same.
