### ISSUE TITLE
Did something break?

### ISSUE THREAD

**Issue by cubantonystark** [kwea123/ngp_pl#25]
Loading Synthetic Nerf Lego breaks with:

ValueError: the number of columns changed from 4 to 3 at row 2; use `usecols` to select a subset and avoid this error

when loading the intrinsics.txt file

The error originates here: datasets/nsvf.py, line 44
    K = np.loadtxt(os.path.join(root_dir, 'intrinsics.txt'),

Seems to be the hard coding on line 27 of datasets/nsvf.py

**Comment by kwea123** [comment]
You should leave the original folder name unchanged. I added this notice in readme.

**Comment by cubantonystark** [comment]
Completely run over that line on the readme, sorry :-)
