### ISSUE TITLE
Problem when using large scale 

### ISSUE THREAD

**Issue by riccardodelutio** [kwea123/ngp_pl#26]
Hi, Thanks a lot for your repo it's very useful! 

I'm having a problem when training a nerf with a large scale factor. For example training on the Lego dataset with a `--scale 8` breaks with the [current repo](https://github.com/kwea123/ngp_pl/commit/6767cb5388f79daf057960f5f0e6f81bd1649642) and returns this error:

`Got cutlass error: Error Internal at: 346`

However, this problem didn't appear with a previous version of your repo. It seems to trace back to the new `calc_dt` function in  raymarching.cu intorduced in the [fix volume rendering condition bug](https://github.com/kwea123/ngp_pl/commit/8e471ccd114691eb4b030318dd1c137a07753a3d#r79095693). 

I see that in the old version the scale was used whereas it isn't used in the new one. Could you help me understand the difference between these two? 

Thanks!

**Comment by riccardodelutio** [comment]
When digging in a bit more I found the model is actually evaluating a lot more samples per ray with the new code (often the `MAX_SAMPLE`) was the old `calc_dt` returning a too low number of samples to evaluate?

**Comment by kwea123** [comment]
I'm still debugging to match the original implementation for real scenes (`scale>0.5`). Therefore anything with `scale>0.5` was never tested and never used...

**Comment by kwea123** [comment]
Hi, just push the code to support large `scale` now. Please tell me if the problem persists

**Comment by riccardodelutio** [comment]
I see thanks, reducing the `batch_size` or the `MAX_SAMPLES` solves the problem for now so it was just a memory problem throwing an uninformative cuda error.. Also I'm using an RTX A6000 so probably the problem is more severe with other GPUs. Thanks!

**Comment by riccardodelutio** [comment]
> Hi, just push the code to support large `scale` now. Please tell me if the problem persists

Great, thanks will try now!

**Comment by riccardodelutio** [comment]
Unfortunately, it seems like it's not solved, I still have to make the batch_size smaller. Also now where it should predict objects with large depths it puts objects very close to the camera. And when training instant-ngp with the same data and settings this doesn't happen.

**Comment by kwea123** [comment]
What scene are you using that require such a large scale? First if the `scale` is large, it means we need more density grids, so more memory consumption, therefore we can only feed a smaller batch size, this is reasonable.
Second, "it puts objects very close to the camera" this problem actually occurs in one of my test data, and I'm still debugging for it, but others (like the fox data and other llff_data) work fine for now. If you have any idea you're welcome to share!

**Comment by riccardodelutio** [comment]
Yes I agree memory consumption makes sense, I was just surprised that from one version to a few later there was a large increase, but I guess the first version I used wasn't sampling properly along rays for large scale factors and the new one is. I'm working on driving scenes, I'll try to debug that too on my scene and let you know what I find, thanks!

**Comment by kwea123** [comment]
The phenomenon of "putting everything in front of each camera" still occurs on *some* scenes, and I also observe this on the original instant-ngp (some scenes cannot train successfully, or trains roughly good but with a lot of floaters). If someone has insight on it, you are welcome to share.

That being said, among many data I've tried (nerf_llff_data, mipnerf 360 data and fox, with different `scale`s varying from `2.0` to `4.0`), most of them train successfully, so I think the `scale` problem is resolved.
