### ISSUE TITLE
do you have RayMarcher's backward function?

### ISSUE THREAD

**Issue by lhb-sjtu** [kwea123/ngp_pl#27]

**Comment by kwea123** [comment]
I think it's impossible. It depends on the occupancy grid which is a bitfield, and you cannot differentiate bits

**Comment by lhb-sjtu** [comment]
thank you

**Comment by lhb-sjtu** [comment]
Can the rays_o and rays_d  be differentiated like an indicator function?

**Comment by lhb-sjtu** [comment]
yes！it works

**Comment by kwea123** [comment]
Now I get your question, yes, it's possible to differentiate w.r.t `rays_o` and `rays_d`. This allows for intrinsics and extrinsics optimization. I have implemented the backward operation, once the test is done I will upload to master.

**Comment by lhb-sjtu** [comment]
ok！thanks
