### ISSUE TITLE
CUDA error when training on custom dataset

### ISSUE THREAD

**Issue by Wuziyi616** [kwea123/ngp_pl#29]
Hi, thank you again for this great work. I encountered a CUDA error `RuntimeError: CUDA error: an illegal memory access was encountered` when training on my custom data rendered from Blender ([Kubric](https://github.com/google-research/kubric), to be more precise). The strange thing is that this bug is not reproducible -- sometimes it happens, sometimes not (using different seeds), and the trackback points to different lines of code each time. One example trackback looks like:
```
... skip all the PyTorch-Lightning related lines
File ".../ngp_pl/finetune.py", line 78, in validation_step                                                                                                             
    results = self(batch, split='test')                                                              
  File ".../anaconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)                                                            
  File ".../ngp_pl/train.py", line 79, in forward                                                                                                                        
    return render(self.model, batch_data['rays'], **kwargs)                                                                                                                                                
  File ".../ngp_pl/models/rendering.py", line 37, in render                                                                                                              
    results = render_func(model, rays_o, rays_d, hits_t, **kwargs)                                                                                                                                         
  File ".../anaconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)                                                                     
  File ".../ngp_pl/models/rendering.py", line 88, in __render_rays_test
    valid_mask = ~torch.all(dirs == 0, dim=1)                                                        
RuntimeError: CUDA error: an illegal memory access was encountered
```
I know it's very hard to debug this given only the error message, but it's a bit tricky to share the code because I modify some parts of it. So I just want to ask if, by any chance, anyone has encountered this error, and what could be the reason for it?

**Comment by Wuziyi616** [comment]
Most frequently this bug happens in `RayMarcher.forward()`, maybe something wrong with `raymarching_train` kernel?

**Comment by kwea123** [comment]
Hi, are you able to share the data?

**Comment by Wuziyi616** [comment]
Hi @kwea123  thanks for the reply. So I've looked into the CUDA code a bit:

1. I recognized that the error always happens after RayMarching, either its train version or its test version.
2. From my understanding, `illegal memory access` may be caused by `index out of range` in the CUDA code? And looking in raymarching kernels, there is this line `const bool occ = density_bitfield[idx/8] & (1<<(idx%8));` ([here](https://github.com/kwea123/ngp_pl/blob/2744df4e4101a32b212aea3c927df321c6727640/models/csrc/raymarching.cu#L220) and [here](https://github.com/kwea123/ngp_pl/blob/2744df4e4101a32b212aea3c927df321c6727640/models/csrc/raymarching.cu#L383)).
3. So, I'm thinking maybe this error is caused by `idx/8` is larger than the number of element of `density_bitfield` array? I first print the size/dtype of it and get:
```
desnity_bitfield.shape torch.Size([262144])
density_bitfield.dtype torch.uint8
```
4. Then, I add a line `if (idx / 8 >= 262144) {printf("Skip idx/8: %d\n", idx / 8); break;}` right before where the indexing operation happens (e.g. between these [2 lines](https://github.com/kwea123/ngp_pl/blob/2744df4e4101a32b212aea3c927df321c6727640/models/csrc/raymarching.cu#L219-L220)).
5. Surprisingly, there are many out-of-range cases happening! This is what I got during training for just 10 steps:
```
Epoch 0:   4%|██████▏                                                                                                                                       | 44/1000 [00:01<00:42, 22.55it/s, loss=0.0001]
desnity_bitfield.shape torch.Size([262144])
density_bitfield.dtype torch.uint8
Epoch 0:   4%|██████▎                                                                                                                                      | 45/1000 [00:01<00:41, 22.98it/s, loss=9.5e-05]
desnity_bitfield.shape torch.Size([262144])                                                                                                                                                                
density_bitfield.dtype torch.uint8         
Epoch 0:   5%|██████▍                                                                                                                                     | 46/1000 [00:01<00:40, 23.40it/s, loss=9.44e-05]
desnity_bitfield.shape torch.Size([262144])                                                                                                                                                                
density_bitfield.dtype torch.uint8         
Epoch 0:   5%|██████▋                                                                                                                                      | 47/1000 [00:01<00:40, 23.81it/s, loss=9.4e-05]
desnity_bitfield.shape torch.Size([262144])                                                                                                                                                                
density_bitfield.dtype torch.uint8         
Epoch 0:   5%|██████▋                                                                                                                                     | 48/1000 [00:01<00:39, 24.23it/s, loss=9.21e-05]
desnity_bitfield.shape torch.Size([262144])                                                                                                                                                                
density_bitfield.dtype torch.uint8         
Epoch 0:   5%|██████▉                                                                                                                                      | 49/1000 [00:01<00:38, 24.53it/s, loss=8.7e-05]
desnity_bitfield.shape torch.Size([262144])
density_bitfield.dtype torch.uint8                                                                                                                                                                         
Epoch 0:   5%|███████                                                                                                                                     | 50/1000 [00:02<00:38, 24.93it/s, loss=8.48e-05]
desnity_bitfield.shape torch.Size([262144])
density_bitfield.dtype torch.uint8
Epoch 0:   5%|███████▏                                                                                                                                    | 51/1000 [00:02<00:37, 25.33it/s, loss=8.33e-05]
desnity_bitfield.shape torch.Size([262144])
density_bitfield.dtype torch.uint8
Skip idx/8: 545344                                                                                                                                                                                         
Epoch 0:   5%|███████▎                                                                                                                                    | 52/1000 [00:02<00:36, 25.73it/s, loss=7.97e-05]
desnity_bitfield.shape torch.Size([262144])
density_bitfield.dtype torch.uint8
```
6. After I did this skipping in both train and test version and raymarching, this error never happen again. However, the performance also drops a lot. I think this is because I'm doing `break` instead of `continue`. But this proves my assumptions that, the but is caused by index out of range? Do you have any insight why this could happen? And any suggestions to fix this?

**Comment by Wuziyi616** [comment]
BTW, I discovered this issue when using a training script written by myself instead of `train.py`. I was doing something similar to fine-tuning a NeRF model from timestep `t` to timestep `t+1` (that's why I cannot share the code/data..), but in general the logic/loss are similar to your implementation of `train.py`.

After seeing this out-of-range issue, I also tested the code in your original `train.py` and this also happens. To my surprise, that didn't break the code, i.e. the program was still running smoothly and got very high PSNR on my custom data.

**Comment by Wuziyi616** [comment]
OK so my current workaround is, if `idx/8` is larger than the size of `density_bitfield`, I'll directly set `occ=false;`, so that we will skip until next voxel. On my custom data this leads to similar performance as previous runs that didn't trigger the error.

**Comment by kwea123** [comment]
Sorry for the inconvience, this was cause by not clipping the `nx` `ny` `nz` to `[0, grid_size-1]`. In the code you're using the value can go to `grid_size` and that cause out of bound error. I reverted to the working version, where I clip the value into the correct range. Now the error shouldn't appear again. Can you pull the code and try again?

**Comment by kwea123** [comment]
I'm also surprised that with the bad code the training still works..

**Comment by Wuziyi616** [comment]
Haha no worries! Glad my debugging helps figure out the real issue. I cannot try it now but I think it should work. Will reopen the issue if it doesn't.

**Comment by Wuziyi616** [comment]
OK it works smoothly
