### ISSUE TITLE
About the performance of NeRF

### ISSUE THREAD

**Issue by Zaki0207** [kwea123/ngp_pl#30]
This for your work, that's very great! But I have a puzzle about customizing datasets: I get the estimated pose through COLMAP, then get the trained model through your repo code (after 10K~100K iter).
However, the result is not great, like this:

https://user-images.githubusercontent.com/41622990/180963872-2e4f8438-7989-4e45-bdbf-7bfd6da37861.mp4

It can't reach the similar performance as NeRF's demo(like lego and others...). So, I think maybe it is related to the accuracy of pose.
Can you give me some suggestions to improve it？

**Comment by kwea123** [comment]
Yes, I think it's due to incorrect pose by COLMAP, some of my experiments show that the pose is crucial to the success, and re-estimating the pose is required in some cases. Can you try automatic reconstruction with quality set to "Extreme"?
