### ISSUE TITLE
A problem occurred before the training was completed

### ISSUE THREAD

**Issue by helcpp** [kwea123/ngp_pl#33]
Thank you so much for such a great job.

My system environment is as follows:

OS: win11+wsl2+ubuntu20.04
Graphic Card: 1660ti 6G
RAM: 40G

I had no problems with my training until you updated the gui code. Today I updated the latest repository and had the following problem.

> (ngp_pl) gzx@HelloWorld:~/code/ngp_pl$  /usr/bin/env /home/gzx/anaconda3/envs/ngp_pl/bin/python /home/gzx/.vscode-server/extensions/ms-python.python-2022.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 37035 -- /home/gzx/code/ngp_pl/train.py --root_dir ../../datasets/nerf/Synthetic_NeRF/Lego/ --exp_name Lego --num_epochs 1 
> GridEncoding: Nmin=16 b=1.31951 F=2 T=2^19 L=16
> Using 16bit native Automatic Mixed Precision (AMP)
> GPU available: True, used: True
> TPU available: False, using: 0 TPU cores
> IPU available: False, using: 0 IPUs
> HPU available: False, using: 0 HPUs
> Loading 100 train images ...
> 100it [00:01, 50.29it/s]
> Loading 200 test images ...
> 200it [00:03, 51.64it/s]
> LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
> Epoch 0:  83%|████████████████ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).y=30.00, train/psnr=29.70]
> ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
> ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
> ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
> ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
> ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
> ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
> ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
> Traceback (most recent call last):
>   File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1134, in _try_get_data
>     data = self._data_queue.get(timeout=timeout)
>   File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/queue.py", line 179, in get
>     self.not_empty.wait(remaining)
>   File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/threading.py", line 306, in wait
>     gotit = waiter.acquire(True, timeout)
>   File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
>     _error_if_any_worker_fails()
> RuntimeError: DataLoader worker (pid 1314) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/gzx/code/ngp_pl/train.py", line 264, in <module>
>     trainer.fit(system, ckpt_path=hparams.ckpt_path)
>   File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
>     self._call_and_handle_interrupt(
>   File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
>     return trainer_fn(*args, **kwargs)
>   File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
>     results = self._run(model, ckpt_path=self.ckpt_path)
>   File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
>     results = self._run_stage()
>   File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
>     return self._run_train()
>   File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1353, in _run_train
>     self.fit_loop.run()
>   File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
>     self.advance(*args, **kwargs)
>   File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 269, in advance
>     self._outputs = self.epoch_loop.run(self._data_fetcher)
>   File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 205, in run
>     self.on_advance_end()
>   File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 255, in on_advance_end
>     self._run_validation()
>   File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 309, in _run_validation
>     self.val_loop.run()
>   File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
>     self.advance(*args, **kwargs)
>   File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 154, in advance
>     dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
>   File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
>     self.advance(*args, **kwargs)
>   File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 112, in advance
>     batch = next(data_fetcher)
>   File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 184, in __next__
>     return self.fetching_function()
>   File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 259, in fetching_function
>     self._fetch_next_batch(self.dataloader_iter)
>   File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 273, in _fetch_next_batch
>     batch = next(iterator)
>   File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
>     data = self._next_data()
>   File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1330, in _next_data
>     idx, data = self._get_data()
>   File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1286, in _get_data
>     success, data = self._try_get_data()
>   File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1147, in _try_get_data
>     raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
> RuntimeError: DataLoader worker (pid(s) 1314) exited unexpectedly
> Epoch 0:  83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                        | 1000/1200 [01:12<00:14, 13.70it/s, loss=0.00104, train/s_per_ray=30.00, train/psnr=29.70]

I don't know what happened. If you know the cause of this problem, please let me know.

**Comment by helcpp** [comment]
I am sorry to bother you.

I have fixed the problem. Your code is perfectly fine. 

The reason for this problem was that I installed docker and the installation automatically changed the shared memory size of my linux subsystem. Once I reset the shared memory, the problem disappeared.

**Comment by kwea123** [comment]
I also encountered this error with my wsl... due to insufficient shared memory. Currently I load all the data (training and validation) to RAM in training, so it would cost a lot RAM usage. My current workaround (if increasing RAM is impossible) is to comment out the validation dataloader (so to skip validation, only training), and use `.ipynb` to validate once the training finishes.
