### ISSUE TITLE
The error when installing Cuda extension!

### ISSUE THREAD

**Issue by liang3588** [kwea123/ngp_pl#34]
Processing e:\codes\ngp_pl-master\ngp_pl-master\models\csrc
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: vren
  Building wheel for vren (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [915 lines of output]
      running bdist_wheel
.....

      2 errors detected in the compilation of "intersection.cu".
      intersection.cu
      error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6\\bin\\nvcc.exe' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for vren
  Running setup.py clean for vren
Failed to build vren
Installing collected packages: vren
  Running setup.py install for vren ... error
  error: subprocess-exited-with-error

  × Running setup.py install for vren did not run successfully.
  │ exit code: 1
  ╰─> [917 lines of output]
      running install
      C:\ProgramData\Anaconda3\envs\ngp-pl\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      C:\ProgramData\Anaconda3\envs\ngp-pl\lib\site-packages\torch\utils\cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.        warnings.warn(msg.format('we could not find ninja.'))
      C:\ProgramData\Anaconda3\envs\ngp-pl\lib\site-packages\torch\utils\cpp_extension.py:346: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找 不到指定的文件。
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      building 'vren' extension
      creating build
      creating build\temp.win-amd64-3.9
      creating build\temp.win-amd64-3.9\Release
      "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IE:\codes\ngp_pl-master\ngp_pl-master\models\csrc\include -IC:\ProgramData\Anaconda3\envs\ngp-pl\lib\site-packages\torch\include -IC:\ProgramData\Anaconda3\envs\ngp-pl\lib\site-packages\torch\include\torch\csrc\api\include -IC:\ProgramData\Anaconda3\envs\ngp-pl\lib\site-packages\torch\include\TH -IC:\ProgramData\Anaconda3\envs\ngp-pl\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include" -IC:\ProgramData\Anaconda3\envs\ngp-pl\include -IC:\ProgramData\Anaconda3\envs\ngp-pl\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /EHsc /Tpbinding.cpp /Fobuild\temp.win-amd64-3.9\Release\binding.obj /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -O2 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=vren -D_GLIBCXX_USE_CXX11_ABI=0
      binding.cpp
      C:\ProgramData\Anaconda3\envs\ngp-pl\lib\site-packages\torch\include\c10/macros/Macros.h(143): warning C4067: 预处理器指令后有意外标记 - 应输入换行符
      C:\ProgramData\Anaconda3\envs\ngp-pl\lib\site-packages\torch\include\c10/core/TensorImpl.h(2214): warning C4805: “|”: 在操作中将类型“uintptr_t”与类型“bool” 混合不安全
      C:\ProgramData\Anaconda3\envs\ngp-pl\lib\site-packages\torch\include\c10/util/Optional.h(198): warning C4624: “c10::constexpr_storage_t<T>”: 已将析构函数隐式定 义为“已删除”

**Comment by kwea123** [comment]
I saw this message: `UserWarning: Error checking compiler version for cl: [WinError 2] 系统找 不到指定的文件。`

Can you try [this](https://blog.csdn.net/wangmengmeng99/article/details/118719322)? Also, windows is not supported and I don't have time to debug in windows, please use ubuntu
