### ISSUE TITLE
Is there a problem in models/networks?

### ISSUE THREAD

**Issue by liang3588** [kwea123/ngp_pl#35]
In Line 210
w2c_R = poses[:, :3, :3].mT # (N_cams, 3, 3) batch transpose

'mT' there is a bug. Do you mean T? or anything?

**Comment by kwea123** [comment]
Did python yield any error message? `mT` is what I commented, batch transpose, which transposes dimensions 1 and 2 in this case. It is not a bug...

**Comment by liang3588** [comment]
"ngp_pl/models/networks.py", line 210, in mark_invisible_cells
    w2c_R = poses[:, :3, :3].mT # (N_cams, 3, 3) batch transpose
AttributeError: 'Tensor' object has no attribute 'mT'

**Comment by liang3588** [comment]
> "ngp_pl/models/networks.py", line 210, in mark_invisible_cells w2c_R = poses[:, :3, :3].mT # (N_cams, 3, 3) batch transpose AttributeError: 'Tensor' object has no attribute 'mT'

there is the error message

**Comment by liang3588** [comment]
Can I use .permute(0,2,1)?
By the way, I found in the /datasets/ray_utils.py, line 64, get_rays()，there is also a mT? Does it mean transposes dimensions 1 and 2?

**Comment by kwea123** [comment]
I use python3.8 with pytorch 1.12.0, there is no problem, please use the same version as the readme, or you can use `.permute(0, 2, 1)`, yes.
