### ISSUE TITLE
About "test_traj.txt"

### ISSUE THREAD

**Issue by liang3588** [kwea123/ngp_pl#36]
I want to ask an addition question, there is no  test_traj.txt in the downloaded datasets from NSVF. How can I obtained it?
Thank you very much!

**Comment by kwea123** [comment]
It only exists for `TanksAndTemples` and `BlendedMVS`.
For the other synthetic data, test set form a good trajectory.

**Comment by kwea123** [comment]
yes, they are the images from the test set.

**Comment by liang3588** [comment]
OK, I understand that, thank you very much!
