### ISSUE TITLE
what is Tensor().mT operation?

### ISSUE THREAD

**Issue by turtoes** [kwea123/ngp_pl#37]
Hello, Thank you so much for the awesome youtube video and lives as well!! I have learnt a lot from them.
Since I tried to trained my own data from nerf dataset transform.json (generated with instant-ngp colmap2nerf.py),
there is a operation .mT within dataset/ray_utils.py with line "rays_d = rearrange(directions, 'n c -> n 1 c') @ c2w[..., :3].mT".

Can you give me some info about this .mT operation? Somehow I cannot run this line due this operation is missing..
How is this different from normal transpose?

Thanks in advance!!

**Comment by turtoes** [comment]
it is me again... never mind, I have found the description, seems like the newest pytorch operation same as x.transpose(-2, -1)..
https://pytorch.org/docs/stable/tensors.html#torch.Tensor

**Comment by kwea123** [comment]
I added pytorch version (>=1.11.0) constraint in readme

**Comment by kwea123** [comment]
changed to `einops.rearrange`
