### ISSUE TITLE
Is there support for 3d texture export?

### ISSUE THREAD

**Issue by yohannes-taye** [kwea123/ngp_pl#40]
Thank you for your implementation and Great Work! I looked through the code but I was not able to find a `.vol` export similar to your previous nerf implementation [here](https://github.com/kwea123/nerf_pl/blob/master/extract_mesh.ipynb). Would the same code work on this model?  If not what suggestions do you have to export the volume to a 3d texture?

**Comment by kwea123** [comment]
Hi, since the texture extraction didn't really have high quality, I didn't re-implement it here (and probably won't until I find better algorithm). You can follow my nerf_pl to do it though.
