### ISSUE TITLE
train colmap data 

### ISSUE THREAD

**Issue by jianglh-WHU** [kwea123/ngp_pl#42]
Hey!Thanks for your excellent work!
I have three questions:
1. instrinsics usually is the format like :
<img width="196" alt="image" src="https://user-images.githubusercontent.com/71580859/184541728-c0b0a251-efd2-4e39-add9-d9fbbaa6d4fd.png">
so can you tell me what's the instrinsics mean?

2. Have you ever met this error? I don't know which step is wrong
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/71580859/184541520-5a45b990-16f7-44ee-bf90-0e27cd8e55da.png">
3. How can I use colmap data to train directly?To other words,how can i get bounds and intrinsics for my custom photos?
Thanks a lot!!!

**Comment by jianglh-WHU** [comment]
sorry,you can close this issue

**Comment by QXmX29** [comment]
I met the same problem T^T So how did you solved this?

**Comment by QXmX29** [comment]
Sorry but I met a problem like `.../intrinsics.txt not found.`, do you know  why and how to solve it?
My data folder contains file "poses_bounds.npy", folder "images", and folder "sparse/0" which contains 4 .bin files

**Comment by jianglh-WHU** [comment]
hi, I guess you use the default NSVF dataset, you can choose to use the colmap dataset

**Comment by QXmX29** [comment]
> hi, I guess you use the default NSVF dataset, you can choose to use the colmap dataset

Oh, I forgot to add `--dataset_name colmap`. Thank you very much!
