### ISSUE TITLE
How to extract mesh

### ISSUE THREAD

**Issue by ZhangLei999** [kwea123/ngp_pl#47]
Great work!
Instant_ngp can extract mesh from images. How does that re-implement in your work?

**Comment by kwea123** [comment]
After loading the model, use this cell in the notebook
<img width="1047" alt="スクリーンショット 2022-08-26 10 30 37" src="https://user-images.githubusercontent.com/11364490/186803778-f717880f-d785-4235-ad96-0be28173769b.png">

Tune the N and the range, threshold

**Comment by ZhangLei999** [comment]
Thanks

**Comment by silver-obelisk** [comment]
> After loading the model, use this cell in the notebook <img alt="スクリーンショット 2022-08-26 10 30 37" width="1047" src="https://user-images.githubusercontent.com/11364490/186803778-f717880f-d785-4235-ad96-0be28173769b.png">
> 
> Tune the N and the range, threshold

Hi, I wonder how to get mesh with color just like you did in nerf_pl? can ngp_pl also do this?

**Comment by meidachen** [comment]
> > After loading the model, use this cell in the notebook <img alt="スクリーンショット 2022-08-26 10 30 37" width="1047" src="https://user-images.githubusercontent.com/11364490/186803778-f717880f-d785-4235-ad96-0be28173769b.png">
> > Tune the N and the range, threshold
> 
> Hi, I wonder how to get mesh with color just like you did in nerf_pl? can ngp_pl also do this?

Same question.

**Comment by zzm666-ui** [comment]
@silver-obelisk 我也想知道怎么保存带有颜色的mesh，请问你解决了吗？感谢回复！

**Comment by zzm666-ui** [comment]
@meidachen 我也想知道怎么保存带有颜色的mesh，请问你解决了吗？感谢回复！
