### ISSUE TITLE
How are you handling the unbounded 360 scene?

### ISSUE THREAD

**Issue by raywzy** [kwea123/ngp_pl#48]
Great work!!! I am wondering how you are handling the 360 scenes. Do you adopt the similar contraction space like mip-nerf 360 or just follow nerf++?

**Comment by kwea123** [comment]
There is no contraction, in instant-ngp all space is handled equally,  that's why far space reconstruction quality is not as good as the other methods you mentioned. I plan to add a multi-sphere background model in the future.
