### ISSUE TITLE
Gradio Demo ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [kwea123/ngp_pl#49]
Can we have a Gradio Demo of the results (someplace where we can upload a punch of images and it produces the 2d model of it) ?

**Comment by kwea123** [comment]
I don't know how to do it. Do you know?

**Comment by MohamedAliRashad** [comment]
It's quite simple if you have the process of Nerf in a closed function.
What will you need is an account on [huggingface](https://huggingface.co/) and some knowledge of [Gradio](https://gradio.app/) (it's really easy) and upload your huggingface space and let us all enjoy it.

**Comment by kwea123** [comment]
It doesn't seem straightforward to me, besides this project requires colmap reconstruction which I believe cannot be easily integrated (notice that instant-ngp also requires running colmap separately). If someone is interested in integrated, you are welcomed to contribute, but this functionality won't be in my plan.
