### ISSUE TITLE
ModuleNotFoundError: No module named 'vren'

### ISSUE THREAD

**Issue by shsf0817** [kwea123/ngp_pl#51]
Hi @kwea123 ,
Is the 'vren.py' file missing? or i should install 'vren' package?

**Comment by kwea123** [comment]
You need to run the last step [here](https://github.com/kwea123/ngp_pl#software)

**Comment by shsf0817** [comment]
Thanks, the problem is fixed.

**Comment by william0620** [comment]
Hi, is it normal that it cost about an hour to finish installing cuda extension under both my 2080ti and my 3090 server. Thanks!
