### ISSUE TITLE
Great work! Can we run the code on multi-host node?

### ISSUE THREAD

**Issue by Holmes-Alan** [kwea123/ngp_pl#54]
I wonder if the code is based on PL. Is it possible that I run the code on two computers, each with 4GPUs? Something like 

python -m torch.distributed.launch --nproc_per_node 4 --nnodes 2 --node_rank 0 --master_addr='xxx.xxx.xxx.xxx' --master_port='80' train.py

Looking forward to your reply.

**Comment by kwea123** [comment]
It should be possible by setting `devices=4, num_nodes=2` in the trainer:
https://github.com/kwea123/ngp_pl/blob/6b2a66928d032967551ab98d5cd84c7ef1b83c3d/train.py#L264-L274
See more options [here](https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html#init)

I have tested one node with multiple gpus, but didn't test multi-nodes. Please report if it works with multi-nodes, thank you.
