### ISSUE TITLE
About building NSVF Synthetic_NeRF datasets from the original Blender dataset

### ISSUE THREAD

**Issue by Heathcliff-saku** [kwea123/ngp_pl#56]
Hi!  kwea:
     It was a pleasure to follow your work again!
     I recently needed to build dataset from blender and used the script provided by the original author
     The original data format is like （in nerf_pl it worked）：
-------------------------
\train
\test
\val
transform_train.txt
transform_test.txt
transform_val.txt
---------------------------
How do I build the **Synthetic_NeRF** from the **original blender type data** that supported in nerf_pl? 
thanks!

**Comment by Heathcliff-saku** [comment]
Main doubts how **bbox.txt** and **intrinsics.txt** generated

**Comment by kwea123** [comment]
please ask NSVF authors, I didn't create these datasets.
