### ISSUE TITLE
Why is the GUI always black？when I run show_gui.py.

### ISSUE THREAD

**Issue by 1zgh** [kwea123/ngp_pl#57]

**Comment by kwea123** [comment]
please provide the full command you use.

**Comment by 1zgh** [comment]
> please provide the full command you use.

python show_gui.py --root_dir ~/zgh/dataset/lf_data/lf_data/ship/ --dataset_name nerfpp     --exp_name ship    --num_epochs 20 --scale 8.0 
![111](https://user-images.githubusercontent.com/51021442/189286477-61a41784-efed-4c83-be4b-baa22eb22e99.png)

**Comment by kwea123** [comment]
You need `--ckpt_path` with your trained model's path. I'm surprised that it still works though

**Comment by 1zgh** [comment]
Thanks! I thought I could visualize and train at the same time, but i was wrong. 
And I am visualizing the ship. I do not find the definition ad good as the photos.
![222](https://user-images.githubusercontent.com/51021442/189786558-1eebeafa-bfde-48b8-8223-9ee9c4fafe46.png)
Visualize
![001](https://user-images.githubusercontent.com/51021442/189786581-c8ec4c3f-10c9-44c2-be47-b33c002c3bb3.png)
Photo

**Comment by 1zgh** [comment]
I find the reason!  Thanks very much. I will close the issue.

**Comment by rap64** [comment]
> 谢谢！我以为我可以同时观想和训练，但我错了。我正在想象这艘船。我不觉得定义广告像照片一样好。 ![222](https://user-images.githubusercontent.com/51021442/189786558-1eebeafa-bfde-48b8-8223-9ee9c4fafe46.png)可视化![001](https://user-images.githubusercontent.com/51021442/189786581-c8ec4c3f-10c9-44c2-be47-b33c002c3bb3.png)照片

How did you solve this problem？
