### ISSUE TITLE
How to generate mesh from trained model?

### ISSUE THREAD

**Issue by cooked-sashimi** [kwea123/ngp_pl#58]
Hi, thank you for this repository. I was wondering how we would generate a mesh from the model, or it is not implemented yet I'd be happy to make a PR to do this maybe something similar to [this](https://github.com/qway/nerfmeshes/blob/master/src/mesh_nerf.py)? If you could give some high level pointers it'd be great

**Comment by kwea123** [comment]
I have included an example in `test.ipynb` cell 6. It extracts mesh without texture. For textured mesh there still isn't any good method.
