### ISSUE TITLE
Planning to support datasets with background?

### ISSUE THREAD

**Issue by morsingher** [kwea123/ngp_pl#6]
Hi, thanks for open sourcing this amazing work! I was wondering if there is any plan to support more realistic datasets without object masks (e.g. the plain and simple T&T instead of the preprocessed from NSVF)? I guess so because supporting custom datasets (with COLMAP?) is on the TODO list, but asking just in case :) thank you again!

**Comment by kwea123** [comment]
Yes, it's my next step!
