### ISSUE TITLE
Large batch_size leading to "Got cutlass error: Error Internal at: 346"

### ISSUE THREAD

**Issue by JasonLSC** [kwea123/ngp_pl#64]
Hi! Thanks a lot for this great repository !

Have you ever come across this error "Got cutlass error: Error Internal at: 346" when using large batch_size? 

I based my current research project on ngp_pl project, but I have to generate the full image rather than random rays in each iteration. It leads to large batch_size during training. However, when batch_size is set to 40000, the training is crashed with above error. 

I have search solutions for this problem. It seems related with tiny-cuda-nn library?

**Comment by kwea123** [comment]
> It seems related with tiny-cuda-nn library?

I think so, and I also encountered it and haven't found solution yet.
https://github.com/NVlabs/instant-ngp/issues/455

However I don't really understand why you need to generate the full image every step? Even without error the training will be extremely slow if you do that. You can do testing every epoch by setting this to `1`
https://github.com/kwea123/ngp_pl/blob/6b2a66928d032967551ab98d5cd84c7ef1b83c3d/train.py#L265
