### ISSUE TITLE
Floating point exception(Core dumped) when i changed code to pytorch from pytorch lighting

### ISSUE THREAD

**Issue by pira998** [kwea123/ngp_pl#67]
Trying to Fix #66
<img width="735" alt="Screenshot 2022-09-17 at 15 17 53" src="https://user-images.githubusercontent.com/46839677/190850927-2dfc4f1d-873e-41bf-ba81-6c234405011b.png">

**Comment by kwea123** [comment]
The code only works for 16bit training, so if you want to use native pytorch code, you need `amp` to handle this. I don't know how to write it in native pytorch and it's a lot easier in pytorch-lightning.

Also I do not understand why you want to change the training code to pytorch while all functionalities are available in pytorch-lightning and are easier to write. If it is for personal purpose, please do not open pull request for it.
