### ISSUE TITLE
Effect of the LLFF "fern" scene

### ISSUE THREAD

**Issue by Yukun66** [kwea123/ngp_pl#70]
I also have another 2 questions: 
  1. My effect of the "fern" scene is not as good as yours which is shown on your `readme.md` page. I've used the default parameters. So I want to ask what parameters you've used to generate the effect of the "fern" scene.

  2. If I want to input some large-scale scenes, what parameters should I modify in NGP? I tried to change the arg "scale"  while the effect got worse. Should I change the "scale"? Or what about the layers number of the encoding network or the rgb_net network? 

Thanks!

**Comment by kwea123** [comment]
I've tried all llff scenes, they work without problem, although the quality is less than that of nerf. I don't remember the parameters now, I will show you once I have them.

For large-scale scenes, you need to increase `scale` to e.g. `8` or `16`. The network parameters can remain the same.

**Comment by kwea123** [comment]
This command
```
python train.py --root_dir /home/ubuntu/data/nerf_data/nerf_llff_data/fern --dataset_name colmap --exp_name fern --num_epochs 10 --scale 2.0 --downsample 0.25
```
works for `fern`. I will add a benchmark file for all `llff` scenes soon.
