### ISSUE TITLE
Question about "opacity" in Volume rendering

### ISSUE THREAD

**Issue by kevin2000A** [kwea123/ngp_pl#71]
Hello! I have a problem with the calculation of “opacity”. 
(https://github.com/kwea123/ngp_pl/blob/7ae0c2835af8032948a3f0eeb82e6500e3aa9526/models/csrc/volumerendering.cu#L27-L44)
The opacity of a ray should be $1-\prod_{i}(1-a_i)$.
But in the code, the opacity is $\sum_{i}a_i T_i$.

**Comment by Yukun66** [comment]
Probably because there are two types of opacity: one for a ray, or for primitives. I think the principle of the "opacity" is if it could be seen, whatever by either type.

**Comment by kwea123** [comment]
notice that $T$ is multiplied by $1-a_i$ each time (L38), so it's actually $1-\prod_{i}(1-a_i)$ like what you write
