### ISSUE TITLE
Scale=16 but Lego gets fragmentization

### ISSUE THREAD

**Issue by Yukun66** [kwea123/ngp_pl#72]
Hi~ Kwea, I've trained your model on the "Lego" scene. It works well in the `scale=0.5` condition, while doesn't work when I set `scale=16`. Here are my results. Could you please help me to find out where I'm wrong or is there any bug in the code? Thanks! 

![001](https://user-images.githubusercontent.com/71137799/192149530-2f89ed6b-f690-4ce9-bdef-c0dee99bbf19.png)

![010](https://user-images.githubusercontent.com/71137799/192149535-77c2475b-1519-47c9-9f66-5735ec924bdd.png)

**Comment by Yukun66** [comment]
Hi, I find that the training data and test data are loaded separately, so the center and pose_avg are calculated twice. Could this be a problem? What if loaded them together and calculate the pose parameters at one time? Thanks~

**Comment by kwea123** [comment]
by default `scale>0.5` uses a black background:
https://github.com/kwea123/ngp_pl/blob/7ae0c2835af8032948a3f0eeb82e6500e3aa9526/models/rendering.py#L155-L159

so the white background in synthetic data becomes white cloud like you have here. If you really need `scale=16` (I don't know why you have to though), manually change the background to white here (and in testing too)
