### ISSUE TITLE
Question about gui

### ISSUE THREAD

**Issue by william0620** [kwea123/ngp_pl#73]
Hi, @kwea123 ,first of all, thanks for your awesome code! I got some questions about GUI. I could train datasets form llff data ,but when it comes to test part with show_gui, the gui became a dark page like this:
![微信图片_20220927222404](https://user-images.githubusercontent.com/68418870/192554131-df44cc8a-ce93-496c-920a-2606025c4382.png)

Thanks!

**Comment by kwea123** [comment]
what is your command?

**Comment by william0620** [comment]
@kwea123 Hi, for training part, the command I use is python train.py --root_dir <root-for-fern> -dataset_name colmap --exp_name fern --num_epochs 10 --scale 2.0 --downsample 0.25 
As for testing part(GUI), the command I used is python show_gui.py --root_dir <root-for-fern> -dataset_name colmap --exp_name fern --num_epochs 10 --scale 2.0 --downsample 0.25.

**Comment by kwea123** [comment]
for gui you need to provide the checkpoint by `--ckpt_path <path/to/.ckpt>`. I have updated the readme for this unclarity.
