### ISSUE TITLE
sigma net different from origin instant-ngp

### ISSUE THREAD

**Issue by cv-lab-x** [kwea123/ngp_pl#74]
hi, thanks for your great work!
about the sigma net in your codes, why use exp(h) instead of using mlp layer as the origin instant ngp?
def density(self, x, return_feat=False):
        """
        Inputs:
            x: (N, 3) xyz in [-scale, scale]
            return_feat: whether to return intermediate feature

        Outputs:
            sigmas: (N)
        """
        x = (x-self.xyz_min)/(self.xyz_max-self.xyz_min)
        h = self.xyz_encoder(x)
        sigmas = TruncExp.apply(h[:, 0])
        if return_feat: return sigmas, h
        return sigmas 
looking forward to your reply! thanks!
@kwea123

**Comment by kwea123** [comment]
they have exponential activation at the end too.
