### ISSUE TITLE
Issue with small batch sizes

### ISSUE THREAD

**Issue by AlexRoss-WHS** [kwea123/ngp_pl#75]
Hi, I noticed that setting `--batch_size` to a very small number (e.g. `--batch_size 10`) causes training to crash after a while, with a floating point exception on the backwards pass. Do you have any idea what causes this?

**Comment by kwea123** [comment]
What is the error message? I suspect that it's due to tiny-cuda-nn since a too large batch size (>32768) also causes crash

**Comment by AlexRoss-WHS** [comment]
Thanks for the quick answer. The error message is : `Process finished with exit code 136 (interrupted by signal 8: SIGFPE)`

**Comment by kwea123** [comment]
Hmm, it seems not a `tiny-cuda-nn` error, but I have no idea what causes this. But do you really need such a small batch size?

**Comment by AlexRoss-WHS** [comment]
No, I don't need small batches. I just came across the error and was wondering what causes it.

**Comment by kwea123** [comment]
Ok, I don't have idea, and thankfully it won't hinder anything.

**Comment by anyeZHY** [comment]
> Thanks for the quick answer. The error message is : `Process finished with exit code 136 (interrupted by signal 8: SIGFPE)`

@AlexRoss-WHS I have encountered the same problem. May I ask how you solved it at that time? Thank you!

**Comment by lxndrrss** [comment]
@anyeZHY I did not solve it. Using very small batchsizes is not really something that is useful, so there was no need to investigate further.
