### ISSUE TITLE
Question about test problem

### ISSUE THREAD

**Issue by william0620** [kwea123/ngp_pl#76]
Hi @kwea123 , it's me again. The reason I didn't reply the last issue is beacuse I was struggling with the environment problem, and I'm now stucking with the test problem as follow:
`RuntimeError: Error(s) in loading state_dict for NGP:
	Unexpected key(s) in state_dict: "density_grid", "grid_coords".`

**Comment by william0620** [comment]
Update: I used the epoch=9.ckpt at first, then I used epoch=9_slim.ckpt, and it works without error. What's the differemce between two ckpts. Meanwhile the fern dataset I use when I trained only reached a train/psnr=24.9 test/psnr=23.0 , I used the parametres given in  #70 .

**Comment by william0620** [comment]
Also, another question for test.ipynb. When I tested with fern dataset, the second cell gave an error with 
`RuntimeError                              Traceback (most recent call last)
Input In [5], in <cell line: 2>()
      1 model = NGP(scale=0.5*2).cuda()
----> 2 load_ckpt(model, f'ckpts/{dataset_name}/{scene}/epoch=9_slim.ckpt')

File ~/ngp_pl/utils.py:26, in load_ckpt(model, ckpt_path, model_name, prefixes_to_ignore)
     24 checkpoint_ = extract_model_state_dict(ckpt_path, model_name, prefixes_to_ignore)
     25 model_dict.update(checkpoint_)
---> 26 model.load_state_dict(model_dict)

File ~/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/torch/nn/modules/module.py:1604, in Module.load_state_dict(self, state_dict, strict)
   1599         error_msgs.insert(
   1600             0, 'Missing key(s) in state_dict: {}. '.format(
   1601                 ', '.join('"{}"'.format(k) for k in missing_keys)))
   1603 if len(error_msgs) > 0:
-> 1604     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
   1605                        self.__class__.__name__, "\n\t".join(error_msgs)))
   1606 return _IncompatibleKeys(missing_keys, unexpected_keys)

RuntimeError: Error(s) in loading state_dict for NGP:
	size mismatch for density_bitfield: copying a param with shape torch.Size([786432]) from checkpoint, the shape in current model is torch.Size([524288]).
	size mismatch for xyz_encoder.params: copying a param with shape torch.Size([12602992]) from checkpoint, the shape in current model is torch.Size([12199312]).`

**Comment by kwea123** [comment]
1. please use `_slim.ckpt` in notebook
2. please make sure the `scale` is the same as training, the `size mismatch` is due to bad scale.

**Comment by william0620** [comment]
OK, I can successfully run test.ipynb. But, there remains two problems:
1.The PSNR of fern is 21.82 and FPS is only 1.23, samples per ray reaches 55.91(I think it's because I did not use the distortion loss.
2. The opacity of figure fern is not good.:
![image](https://user-images.githubusercontent.com/68418870/193414886-aab88e01-4894-449a-9f46-f07cd24aa033.png)

**Comment by william0620** [comment]
OK, I can successfully run test.ipynb. But, there remains two problems:
1. I can't generate mp4, since the length of imgs is 1, it seems imgs+=preds sends in an array whose shape is 200*200*3?
![image](https://user-images.githubusercontent.com/68418870/194720160-7670d9f1-76c7-4876-a344-96d5cf244f06.png)

2. the last part which originally should display rays and occupied cells could only display cameras and bounding box0, do I need to adjust the code?
![image](https://user-images.githubusercontent.com/68418870/194720185-4c2a9e53-ac03-46bb-a8f6-84a98206686c.png)

4. Thanks!

**Comment by william0620** [comment]
Thanks a lot!

**Comment by SEUleaderYang** [comment]
Hello, I meet the same problem, and the parameter of scale keep same with the train stage when I run the show-gui srcipt, but I still meet the size mismatch problem, I wonder how you solve this problem, thanks a lot!

**Comment by william0620** [comment]
> Hello, I meet the same problem, and the parameter of scale keep same with the train stage when I run the show-gui srcipt, but I still meet the size mismatch problem, I wonder how you solve this problem, thanks a lot!

@SEUleaderYang I just changed the number of scale, by the way I think you should use the jupyternotebook instead of gui for the first time, for that you can debug. If you got more question, please email me.

**Comment by hypochlorous** [comment]
> 
Hello,would you know how to use the ckpt without _slim correctly in show-gui or where? whats the difference? Is it a more complete model?

**Comment by hypochlorous** [comment]
> > Hello, I meet the same problem, and the parameter of scale keep same with the train stage when I run the show-gui srcipt, but I still meet the size mismatch problem, I wonder how you solve this problem, thanks a lot!
> 
> @SEUleaderYang I just changed the number of scale, by the way I think you should use the jupyternotebook instead of gui for the first time, for that you can debug. If you got more question, please email me.

Hello,would you know how to use the ckpt without _slim correctly in show-gui or where? whats the difference? Is it a more complete model?
