### ISSUE TITLE
What is the reason being `train` dataset length hardcoded to 1000?

### ISSUE THREAD

**Issue by madratman** [kwea123/ngp_pl#78]
Thanks for the great work!

I don't understand why this line is hardcoded to 1000
 https://github.com/kwea123/ngp_pl/blob/2865dbbae14b2313654a8da383dd641e4e825642/datasets/base.py#L19
 
For the original NeRF blender synthetic dataset, the num of training images is 100, but I saw tqdm going to 1000. Debugging through the code to find the reason, I saw this was hardcoded to 1000 in the base class of the dataset. 

So in some sense, for nerf synthetic, are we doing 200 epochs in the [benchmark script](https://github.com/kwea123/ngp_pl/blob/master/benchmarking/benchmark_synthetic_nerf.sh) as compared to 20? 

 
I noticed this when I saw the time taken for 1 epoch is quite large as compared to https://github.com/ashawkey/torch-ngp. Setting that line to `100` makes the epoch speed comparable. 
I suppose we should be inferring the dataset length instead of setting to 100/1000 ofc

**Comment by madratman** [comment]
Here are some runs:

- Y axis is num of epochs, X-axis 
Higher slopes are with fixed dataset length to 100, lower slope cluster corresponds to current main branch (1000)
![image](https://user-images.githubusercontent.com/6305323/193910638-213b8346-89a3-4c37-90f5-23ab75482bda.png)

- Y axis is time taken per epoch, X-axis is num_of_epochs
![image](https://user-images.githubusercontent.com/6305323/193911051-89e152ab-b05b-4f3a-8013-e0de775d1a3b.png)

The slower cluster (higher on Y axis) is with 1000
the faster cluster is with 100

- Train PSNR 
"shorter" curve length correponds to 100

![image](https://user-images.githubusercontent.com/6305323/193911325-4879957c-885c-42f4-b421-75ac6e6de02e.png)

- Loss curves
trimmed this one
![image](https://user-images.githubusercontent.com/6305323/193911571-3671905f-11f0-4ab8-98ef-2c8a599a3085.png)


- Also, I notice not much change in time wrt 8192 and 16384 rays per batch on V100 wrt time, I guess gpu was being underused

**Comment by kwea123** [comment]
> I don't understand why it's set to 1000

This is by experiments, I find that this number allows the to reach comparable results within comparable training time, so I chose this value.

> I saw the time taken for 1 epoch is quite large compared to torch-ngp
I don't remember what is the data size for it, but I remember it takes 10x epoch time to reach the same quality, so it's data size should be around 100, therefore setting that line to 100 makes the epoch speed comparable.

> I suppose we should be inferring the dataset length instead of setting to 100/1000 ofc

The total iterations is `epoch`x`data size`, so in my experiment it corresponds to 20k iterations by default, you can balance `epoch` `data size` whatever you want, it doesn't matter at all, you can even train with 1 epoch with `data size = 20000`, initially I wanted to monitor the training progress (ie val psnr) more so I set more epochs.

**Comment by madratman** [comment]
got it, thanks!
