### ISSUE TITLE
Predicting SDF instead of density?

### ISSUE THREAD

**Issue by morsingher** [kwea123/ngp_pl#8]
Hi, it's me again with another question. I'm thinking of extending this framework to support SDF prediction instead of density. How hard would this be? I mean something like https://lioryariv.github.io/volsdf/ (or NeuS) where you still train from posed images with volume rendering. My naive guess is that you would need to convert the geometry MLP output from SDF to density before rendering and (maybe) change some hyperparameters, but I might be overlooking something. From an implementation point of view, is this something that can be quickly done or does it require major changes to the code? Thank you in advance!

**Comment by kwea123** [comment]
Hi, I am aware of those methods, and am planning to implement too. These requires major changes, and I probably won't open source everything (this is part of my work). I will make announcement!
