### ISSUE TITLE
How to train synthetic dataset (lego) in 5 seconds?

### ISSUE THREAD

**Issue by Kravrolens** [kwea123/ngp_pl#80]
Thanks for your awesome reimplement code of instance-ngp.

When I ran with :
```
python train.py --root_dir /my/data/path \
                --dataset_name nerf \
                --exp_name lego \
                --no_save_test
```
It takes 10 seconds or more for each epoch, how to increase training efficiency? many thanks in advance!

**Comment by kwea123** [comment]
You can decrease this number to decrease the training time for each epoch
https://github.com/kwea123/ngp_pl/blob/d375fbec2d411150bc23d1f24253f15caac91b32/datasets/base.py#L19
