### ISSUE TITLE
About the extrinsics optimization algorithm 

### ISSUE THREAD

**Issue by yzslab** [kwea123/ngp_pl#89]
Hi, 
would you mind sharing some information about the extrinsics optimization algorithm that you implemented? Such as the paper name.

Thanks.

**Comment by kwea123** [comment]
I didn't borrow any paper exactly, just optimizing the dR, dT (delta rotation, delta translation) along with model weights

**Comment by yzslab** [comment]
> I didn't borrow any paper exactly, just optimizing the dR, dT (delta rotation, delta translation) along with model weights

OK, thanks for your reply!
