### ISSUE TITLE
backward function of CUDA

### ISSUE THREAD

**Issue by Yukun66** [kwea123/ngp_pl#92]
Hello, kwea123!  I'm trying to add one CUDA algorithm between the `RayMarcher` and `VolumeRenderer`, but my `backward` function is not working, it seems like it ignores my `backward` function. Could you give me some suggestions to debug? Could please tell me what steps or operations should be required or paid attention to during the backward function design to get it to work? Thank you very much!

**Comment by Yukun66** [comment]
I get it done today, haha! A little step forward to understanding the process of CUDA working~

**Comment by kwea123** [comment]
Sorry for the late reply, I will cover this in my last cuda tutorial video that I will upload today. Basically you need to define a python  class like this
https://github.com/kwea123/ngp_pl/blob/8d04855eb3c2a6924a5f2a9a8eaa3720758fec51/models/custom_functions.py#L162-L173

that implements `forward` and `backward`, and call cuda kernel in the `backward` function which calculates the gradient mathematically

**Comment by Yukun66** [comment]
Thanks! Your tutorial videos are awesome, help me a lot~
