### ISSUE TITLE
A problem occurred in the rendering results

### ISSUE THREAD

**Issue by immortalmin** [kwea123/ngp_pl#93]
Hi, when I used 'room' in nerf_llff_data dataset for training, I found that some rendered pictures became like this? 
![000](https://user-images.githubusercontent.com/42803282/198869931-b0209837-e5d5-4850-b9c4-0527f94210f0.png)
This is my runtime parameter,
`python train.py --root_dir /xxx/nerf_llff_data/horns/ --dataset_name colmap --exp_name horns --num_epochs 2 --batch_size 1024 --lr 5e-3 --eval_lpips --distortion_loss_w 1e-3 --ray_sampling_strategy all_images --downsample 0.125
`
And I didn't change any code in the project. 
However, in other scenarios of nerf_llff_data dataset, this phenomenon does not occur.

**Comment by kwea123** [comment]
The following result is what I obtained without `--distortion_loss_w`, can you try again?
![000](https://user-images.githubusercontent.com/11364490/198874611-431cb805-fade-48cf-ad02-38d5ac929349.png)

**Comment by immortalmin** [comment]
It works. Thank you for your reply.

**Comment by szgy66** [comment]
> It works. Thank you for your reply.

Hello! I refer to your command:
`python train.py --root_dir ./data/colmap/nerf_llff_data/room/ --dataset_name colmap --exp_name room --num_epochs 30 --batch_size 1024 --lr 5e-3 --eval_lpips --ray_sampling_strategy all_images` to train，and `python show_gui.py --root_dir ./data/colmap/nerf_llff_data/room/ --dataset_name colmap --exp_name room --batch_size 1024 --ray_sampling_strategy all_images --eval_lpips --ray_sampling_strategy all_images --ckpt_path ckpts/room/epoch=29_slim.ckpt` to show the result with GUI. But I got thr result as follow:
![image](https://user-images.githubusercontent.com/46223162/232202595-129ff4f0-9333-4748-a3e6-937b84a09907.png)
Its result is in the lower right corner and cannot be adjusted. As shown in part of the results, his effect is very poor. Could you please tell me how to solve it? Thanks!
